### PR TITLE
MSDKUI-1959: Update to Xcode 10.2 and Swift 5.0

### PR DESCRIPTION
**Pull request by ghost**
Xcode 10.2 is new and Travis might not have it yet. If the build fails, we will have to re-build once Travis adds and Xcode 10.2 image.

### CODE REVIEW

**Comment by datasun** [comment]
Would be great if you can also update the main README page. It still says Xcode 10.1 and Swift 4.2 ...

**Comment by otaviohere** [comment]
> Would be great if you can also update the main README page. It still says Xcode 10.1 and Swift 4.2 ...

Nope. README is [correct](https://github.com/heremaps/msdkui-ios/pull/118/files#diff-04c6e90faac2675aa89e2176d2eec7d8).

**Comment by datasun** [comment]
Ah, right, already included ... ;-) Well, done.

**Comment by otaviocc** [comment]
👍

**Pull request merged**
